on: push
jobs:
  cicd:
    # https://github.com/internetarchive/cicd
    uses: internetarchive/cicd/.github/workflows/cicd.yml@main
    with:
      NOMAD_VAR_PORTS: '{ 80 = "http" }'
      # BASE_DOMAIN: 'uncomment line & set value (for non-archive.org deploys)'
      # NOMAD_ADDR:  'uncomment line & set value (for non-archive.org deploys)'
    secrets:
      NOMAD_TOKEN: ${{ secrets.NOMAD_TOKEN }}
